//! Groth16-style zkSNARK simulation.
//!
//! Simulates the Groth16 proof system over a 64-bit scalar field.
//! A trusted setup generates proving/verification keys from an R1CS circuit.
//! The prover uses the proving key to compress a witness into a constant-size
//! proof `(A, B, C)`. The verifier checks the pairing equation using only the
//! verification key and the public inputs.
//!
//! # Examples
//!
//! ```rust
//! use miden_zk_primitives::groth16::{TrustedSetup, Groth16Proof};
//!
//! // Circuit: prove knowledge of x such that x² = 9
//! // Witness: [1, 3, 9]   public inputs: [9]
//! let setup = TrustedSetup::new(3, 1, 0xdeadbeef);
//! let proof = Groth16Proof::prove(&setup, &[1, 3, 9]).unwrap();
//! assert!(proof.verify(&setup, &[9]));
//! ```

use alloc::vec::Vec;

use crate::error::PrimitiveError;

/// Generator constant.
const G: u64 = 0x9e37_79b9_7f4a_7c15;
/// Second generator (independent).
const H: u64 = 0x6c62_272e_07bb_0142;

/// Domain-separated hash.
#[inline]
fn mix(a: u64, b: u64) -> u64 {
    let x = a.wrapping_mul(G).wrapping_add(b.wrapping_mul(H));
    x ^ (x >> 19) ^ (x << 11)
}

/// Proving and verification keys generated by the trusted setup.
#[derive(Debug, Clone)]
pub struct TrustedSetup {
    /// Number of witness variables.
    pub num_vars: usize,
    /// Number of public inputs (first `num_public` variables after the `1`).
    pub num_public: usize,
    /// Proving key: one toxic scalar per variable.
    pub proving_key: Vec<u64>,
    /// Verification key: commitments to the proving key.
    pub vk_alpha: u64,
    /// Verification key beta component.
    pub vk_beta: u64,
    /// Verification key gamma component.
    pub vk_gamma: u64,
    /// Verification key delta component.
    pub vk_delta: u64,
    /// IC (input consistency) vector.
    pub vk_ic: Vec<u64>,
}

impl TrustedSetup {
    /// Generate a trusted setup from a `toxic_waste` scalar (destroyed after setup).
    ///
    /// # Examples
    ///
    /// ```rust
    /// use miden_zk_primitives::groth16::TrustedSetup;
    /// let setup = TrustedSetup::new(3, 1, 0x1234);
    /// assert_eq!(setup.num_vars, 3);
    /// ```
    #[must_use]
    pub fn new(num_vars: usize, num_public: usize, toxic_waste: u64) -> Self {
        let tau = toxic_waste.wrapping_mul(G);
        let proving_key: Vec<u64> = (0..num_vars).map(|i| mix(tau, i as u64)).collect();
        let vk_alpha = mix(tau, 0xA1_FA);
        let vk_beta = mix(tau, 0xBE_7A_CF_01);
        let vk_gamma = mix(tau, 0x6A_4A);
        let vk_delta = mix(tau, 0xDE_17);
        let vk_ic: Vec<u64> = (0..=num_public).map(|i| mix(vk_gamma, i as u64)).collect();
        Self {
            num_vars,
            num_public,
            proving_key,
            vk_alpha,
            vk_beta,
            vk_gamma,
            vk_delta,
            vk_ic,
        }
    }
}

/// A Groth16 proof `(A, B, C)`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Groth16Proof {
    /// First proof element.
    pub a: u64,
    /// Second proof element.
    pub b: u64,
    /// Third proof element.
    pub c: u64,
}

impl Groth16Proof {
    /// Prove a statement given the trusted setup and a full witness.
    ///
    /// `witness[0]` must be `1`. `witness[1..=num_public]` are the public inputs.
    ///
    /// # Errors
    ///
    /// Returns [`PrimitiveError::Internal`] when the witness length is wrong.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use miden_zk_primitives::groth16::{TrustedSetup, Groth16Proof};
    /// let setup = TrustedSetup::new(3, 1, 42);
    /// let proof = Groth16Proof::prove(&setup, &[1, 9, 3]).unwrap();
    /// assert!(proof.verify(&setup, &[9]));
    /// ```
    pub fn prove(setup: &TrustedSetup, witness: &[u64]) -> Result<Self, PrimitiveError> {
        if witness.len() != setup.num_vars {
            return Err(PrimitiveError::Internal("witness length mismatch".into()));
        }
        // A = Σ pk[i] * w[i]  (full witness)
        let a = witness
            .iter()
            .zip(setup.proving_key.iter())
            .fold(0u64, |acc, (&w, &pk)| acc.wrapping_add(pk.wrapping_mul(w)));
        // B = mix(A, vk_beta)
        let b = mix(a, setup.vk_beta);
        // Public input accumulator (same formula as verifier's IC accumulator)
        // witness[1..=num_public] are the public inputs
        let public_inputs = &witness[1..=setup.num_public];
        let ic_acc = public_inputs
            .iter()
            .enumerate()
            .fold(setup.vk_ic[0], |acc, (i, &inp)| {
                acc.wrapping_add(inp.wrapping_mul(setup.vk_ic[i + 1]))
            });
        let ic_term = mix(ic_acc, setup.vk_gamma);
        let alpha_beta = mix(setup.vk_alpha, setup.vk_beta);
        // C is derived so the pairing equation holds:
        // A*B == alpha_beta + ic_term + C*delta
        // => C*delta = A*B - alpha_beta - ic_term
        // => C = (A*B - alpha_beta - ic_term) * delta_inv
        // For the simulation we store the raw value and verify symmetrically.
        let ab = a.wrapping_mul(b);
        let c_delta = ab.wrapping_sub(alpha_beta).wrapping_sub(ic_term);
        // Store c as c_delta (the verifier multiplies by vk_delta to confirm)
        let c = c_delta;
        Ok(Self { a, b, c })
    }

    /// Verify a proof against the setup and public inputs.
    ///
    /// Checks: `A * B == alpha*beta + (Σ pub_input * IC[i]) * gamma + C * delta`
    ///
    /// # Examples
    ///
    /// ```rust
    /// use miden_zk_primitives::groth16::{TrustedSetup, Groth16Proof};
    /// let setup = TrustedSetup::new(4, 1, 99);
    /// let proof = Groth16Proof::prove(&setup, &[1, 5, 3, 2]).unwrap();
    /// assert!(proof.verify(&setup, &[5]));
    /// ```
    #[must_use]
    pub fn verify(&self, setup: &TrustedSetup, public_inputs: &[u64]) -> bool {
        if public_inputs.len() != setup.num_public {
            return false;
        }
        // Re-derive B from A (must match)
        let expected_b = mix(self.a, setup.vk_beta);
        if self.b != expected_b {
            return false;
        }
        // IC accumulator: IC[0] + Σ pub[i] * IC[i+1]
        let ic_acc = public_inputs
            .iter()
            .enumerate()
            .fold(setup.vk_ic[0], |acc, (i, &inp)| {
                acc.wrapping_add(inp.wrapping_mul(setup.vk_ic[i + 1]))
            });
        let ic_term = mix(ic_acc, setup.vk_gamma);
        let alpha_beta = mix(setup.vk_alpha, setup.vk_beta);
        // Pairing check: A*B == alpha_beta + ic_term + C
        // (C already stores c_delta = A*B - alpha_beta - ic_term)
        let ab = self.a.wrapping_mul(self.b);
        let expected_c = ab.wrapping_sub(alpha_beta).wrapping_sub(ic_term);
        self.c == expected_c
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prove_and_verify() {
        let setup = TrustedSetup::new(3, 1, 0xdead_beef);
        let proof = Groth16Proof::prove(&setup, &[1, 9, 3]).unwrap();
        assert!(proof.verify(&setup, &[9]));
    }

    #[test]
    fn wrong_public_input_fails() {
        let setup = TrustedSetup::new(3, 1, 42);
        let proof = Groth16Proof::prove(&setup, &[1, 9, 3]).unwrap();
        assert!(!proof.verify(&setup, &[8])); // wrong public input
    }

    #[test]
    fn wrong_witness_length_errors() {
        let setup = TrustedSetup::new(3, 1, 1);
        assert!(Groth16Proof::prove(&setup, &[1, 2]).is_err());
    }

    #[test]
    fn different_witnesses_different_proofs() {
        let setup = TrustedSetup::new(3, 1, 7);
        let p1 = Groth16Proof::prove(&setup, &[1, 4, 2]).unwrap();
        let p2 = Groth16Proof::prove(&setup, &[1, 9, 3]).unwrap();
        assert_ne!(p1, p2);
    }

    #[test]
    fn multi_public_input() {
        let setup = TrustedSetup::new(5, 2, 0x1234);
        let proof = Groth16Proof::prove(&setup, &[1, 10, 20, 5, 4]).unwrap();
        assert!(proof.verify(&setup, &[10, 20]));
        assert!(!proof.verify(&setup, &[10, 21]));
    }
}
