//! Range proof using Miden VM's native `u32gte` / `u32lte` instructions.
//!
//! Proves `lo ≤ value ≤ hi` where all three values are u32 (< 2³²).
//! The STARK proof is generated by the Miden prover and can be verified
//! by any party with access to the public parameters (`lo`, `hi`).

use crate::utils::{prove_program, verify_program, ProofBundle};

/// Build the MASM program that asserts `value ∈ [lo, hi]`.
fn range_src(value: u64, lo: u64, hi: u64) -> String {
    format!(
        "begin\n    \
         push.{value}\n    \
         push.{lo}\n    \
         u32gte\n    \
         assert\n    \
         push.{value}\n    \
         push.{hi}\n    \
         u32lte\n    \
         assert\n\
         end"
    )
}

/// Prove that `lo ≤ value ≤ hi`.
///
/// All three arguments must be valid `u32` values (< 2³²).
pub fn prove_range(value: u64, lo: u64, hi: u64) -> Result<ProofBundle, String> {
    prove_program(&range_src(value, lo, hi), &[])
}

/// Verify a range proof.
pub fn verify_range(
    value: u64,
    lo: u64,
    hi: u64,
    bundle: &ProofBundle,
) -> Result<(), String> {
    verify_program(&range_src(value, lo, hi), &[], bundle)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore = "generates a real STARK proof (~24 GB RAM); run locally with --ignored"]
    fn test_range_pass() {
        let b = prove_range(25, 18, 120).expect("prove failed");
        verify_range(25, 18, 120, &b).expect("verify failed");
    }
}
